apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: banterop-db
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.banterop.storageClassName }}
